// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pezlxaojqndfmjhllqry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlemx4YW9qcW5kZm1qaGxscXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDAyNDYsImV4cCI6MjA3Mjk3NjI0Nn0.pB2xA50t9_kSwgDV4AWvNi62Ykslhmu9DY19nksa8Sw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});